services:
  - type: web
    name: kvt-ecommerce-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npx prisma migrate deploy && npx prisma db seed && npm start
    envVars:
      - key: DATABASE_URL
        sync: false # User will input their Neon Database URL
      - key: JWT_SECRET
        generateValue: true # Render will automatically generate a secure JWT secret key
      - key: PORT
        value: 10000
